### ISSUE TITLE
[raft] Wrong error messages when trying to repay more then you have debt

### ISSUE THREAD

**Issue by lazarmitic** [raft-fi/app#413]
![Image](https://user-images.githubusercontent.com/7648077/241738191-beca6ab6-c889-4edd-8bd7-f1c0fe827109.png)

1. Collateral error message should now show up.
2. Position after -> Debt -> Should be `0 R` not `-.500.00 R`
3. Position after -> Collateral ratio -> Should be `N/A`
4. Error message for debt input should be: `Repayment amount larger than your outstanding debt`
5. Error message on execute button should be `Repayment amount larger than your outstanding debt`

**Comment by irinelT** [comment]
![PowerToys_EHQfTPVK2E](https://github.com/raft-fi/app/assets/98878781/eca5975d-9253-40b9-be2e-973b88d06ca2)
