### ISSUE TITLE
[raft app] Whitelist/Approve changes by itself

### ISSUE THREAD

**Issue by irinelT** [raft-fi/app#468]
When switching network, the label on the button changes.

![PowerToys_tkhAs35vwW](https://github.com/tempusfinance/raft-app/assets/98878781/84890666-90e3-4adb-a9b4-8a6d558fb06b)

**Comment by ShawTim** [comment]
it's now re-implemented

**Comment by irinelT** [comment]
This issue is not reproducible any more.
