### ISSUE TITLE
Approve R failed

### ISSUE THREAD

**Issue by irinelT** [raft-fi/app#536]
![r7F5FQ89ph](https://github.com/raft-fi/app/assets/98878781/44a8b970-f002-4543-8c35-761276db3389)

![chrome_SNvgh3Eqwl](https://github.com/raft-fi/app/assets/98878781/fabf31cc-0a4d-434f-a101-cae14a0bd4c2)

**Comment by ShawTim** [comment]
this seems to be related to the wallet client which reject the approval request. cannot reproduce

**Comment by irinelT** [comment]
Seems to be working fine now.


https://github.com/raft-fi/app/assets/98878781/6ca8e18e-bc57-4e40-910d-1e468a00f33e
