### ISSUE TITLE
[raft app] Maximum position debt should not be more then 10% of total debt

### ISSUE THREAD

**Issue by lazarmitic** [raft-fi/app#538]
When user is opening or adjusting his position, we should not allow him to have debt more then 10% of total protocol debt.

**Comment by irinelT** [comment]
Works fine.


![MaximumPositionDebtShouldNotBeMoreThen10PercentageOfTotalDebt](https://github.com/raft-fi/app/assets/98878781/c576979b-3159-4c4c-a759-c99c184ea961)
