### ISSUE TITLE
[raft app] In adjust position when empty input loses focus it is automatically populated with zero value

### ISSUE THREAD

**Issue by lazarmitic** [raft-fi/app#553]
1. Delete everything from input field.
2. Click outside of input field.
3. There is 0 in input field.
4. If I want to edit this field, I have to delete 0 first before being able to type in anything.
5. There should be a placeholder 0 in input field and I should be able to type in without having to delete zero.

**Comment by irinelT** [comment]
Works fine now.


https://github.com/raft-fi/app/assets/98878781/23afce87-35b3-4efd-868c-2810c458fbf2
