### ISSUE TITLE
[raft app] Add new collateral icons

### ISSUE THREAD

**Issue by danieledamiani** [raft-fi/app#561]
- ETH
- WETH

https://www.figma.com/file/CAHrE4rIOc0EE6lXZE69wU/Raft-App?type=design&node-id=1188-16484&t=j1JInchoSMQzbN6n-0

**Comment by irinelT** [comment]
New collateral icons were added.


![AddNewCollateralIcons](https://github.com/raft-fi/app/assets/98878781/80e0fb26-82da-413a-8d84-46915a6d9d43)
