### ISSUE TITLE
[raft app] Add currency dropdown

### ISSUE THREAD

**Issue by danieledamiani** [raft-fi/app#562]
https://www.figma.com/file/CAHrE4rIOc0EE6lXZE69wU/Raft-App?type=design&node-id=179-7822&t=j1JInchoSMQzbN6n-0

**Comment by irinelT** [comment]
Currency dropdown looks good.


![AddCurrencyDropdown](https://github.com/raft-fi/app/assets/98878781/1048dcca-1e33-46a8-b7ea-daa156252930)
