### ISSUE TITLE
[Redeem] Values are not updated after user input

### ISSUE THREAD

**Issue by irinelT** [raft-fi/app#603]
1. Switch to `rETH`
2. Type in `499` "Amount to redeem".

![PowerToys_FbITzvBIpG](https://github.com/raft-fi/app/assets/98878781/35c2f385-f63d-4c5a-860a-62c116195295)

Note: It works if you do the steps in opposite order.

**Comment by ShawTim** [comment]
should work now

**Comment by irinelT** [comment]
Seems to work fine now.


![ValuesAreNotUpdatedAfterUserInput](https://github.com/raft-fi/app/assets/98878781/49c133a8-3b2a-409c-be08-c6773afe4620)
