### ISSUE TITLE
[Redeem] Always fails with `rETH`

### ISSUE THREAD

**Issue by irinelT** [raft-fi/app#604]
![PowerToys_vh5WO7URxO](https://github.com/raft-fi/app/assets/98878781/51389215-47d7-453a-812a-c75c50830a98)

**Comment by ShawTim** [comment]
should work now

**Comment by irinelT** [comment]
Works now.



https://github.com/raft-fi/app/assets/98878781/c47875b9-3b62-4c4a-947d-a2e44f97fe15
